spring.application.name=RentFlow

# Server
server.port=8080
server.servlet.context-path=/api

# Logging
logging.level.root=INFO
logging.level.com.rentflow=DEBUG

# Jackson
spring.jackson.serialization.indent-output=true
spring.jackson.time-zone=UTC
